### ISSUE TITLE
Items moved to the trash are still accessible with a public link

### ISSUE THREAD

**Issue by alanclayton** [Rise-Vision/storage-server#115]
Get the public link for a file. Then move that item to trash. Open the link in incognito. The file appears.

Files in trash should not be publicly accessible. 

Link to a file in trash, https://storage.googleapis.com/risemedialibrary-fee1f642-cdd1-4bc4-8f93-1fc97cb00d55/2012-04-12_1620.png

**Comment by alanclayton** [comment]
@fjvallarino Not sure what changed, but I'm unable to replicate this now.

**Comment by tejohnso** [comment]
Might have been a caching issue if the file was moved to trash then quickly checked for access.
