### ISSUE TITLE
When folder in trash has same name as folder in storage, both folders are accessed by Image/Video Folder Widgets.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/storage-server#197]
Steps to reproduce:
1. Create a folder named Videos
2. Upload two .mp4 videos to this folder
3. Move the Videos folder to the trash
4. Create a new folder named Videos
5. Upload a .webm video to this folder
6. Add Video Folder Widget to presentation
7. Add the new Videos folder (containing the single .webm file) to the Video Folder Widget

Result:
The presentation will play all of the videos in both video folders.

How it should work:
Presentation should not have access to the Video folder in trash. It should be playing a single .webm from the new folder.

Chrome Ver:
43.0.2357.81

**Comment by btfrise** [comment]
@fjvallarino You can see an example of this issue here https://www.googleapis.com/storage/v1/b/risemedialibrary-e113f8d6-de1c-4c26-b160-4ef1c4589957/o?prefix=videos%2F

**Comment by fjvallarino** [comment]
@btfrise Yes, I understand the issue. As part of the Trash performance improvements, we changed the structure of GCS buckets. Users should start consuming Storage's API instead, since we merge information from Datastore. Who should I contact regarding the Image/Video Folder widget?

@tejohnso FYI

**Comment by alanclayton** [comment]
@fjvallarino , @donnapep worked on the Storage Component used by Image & Video Widget. Can you confirm we should be doing differently?  @stulees FYI

**Comment by fjvallarino** [comment]
@alanclayton Yes, unfortunately we should change that. If I remember correctly, at some point they were using a tagging API for which a request was made to add content type on the response. I can restore that endpoint if necessary (without the tagging part, of course).

**Comment by fjvallarino** [comment]
@alanclayton Just to clarify, we already have an API storage-client uses and is available for everyone. I mentioned the old endpoint because of the content-type requirement (which the current API endpoint does not return).

**Comment by alanclayton** [comment]
@fjvallarino sorry, not sure I follow what needs to happen. It would be best if you have that discussion w/ @donnapep Thanks

**Comment by donnapep** [comment]
@fjvallarino Are you saying that the storage component should not be making calls directly to `googleapis.com` and should instead communicate via the Storage API?

**Comment by fjvallarino** [comment]
@donnapep Yes, we will have to do that, since we Storage's information is not anymore on GCS only. From storage-client we use the getFiles endpoint to fetch files/directories. Probably you will need the content-type field. Let me know and I'll add it to the response.

**Comment by donnapep** [comment]
@fjvallarino Do you have to be authenticated in order to use that API? If yes, then that's a problem and I will need access to an unauthenticated API. In particular, my code looks for the `selfLink` and `etag` properties for single files, and the `name`, `selfLink`, `contentType`, `updated` and `etag` properties for files in a folder.

Perhaps we can re-activate that other API you had made available to me before and ensure it returns those fields?

**Comment by fjvallarino** [comment]
@donnapep This API is unauthenticated. Let me investigate what the fields beyond contentType are so I can add them to the response.

**Comment by donnapep** [comment]
@fjvallarino Thanks. And can I use this API to request a specific file, or would I need to request an entire folder and search for the file that I need?

**Comment by fjvallarino** [comment]
@donnapep Not currently (it works with folders). In case it's required, we can make that change (I have to check it does not break something else, otherwise we'll have to create a separate endpoint).

**Comment by btfrise** [comment]
@fjvallarino What's the status here?

**Comment by fjvallarino** [comment]
@btfrise, @alanclayton suggested we don't fix this right now. I just forwarded you the email.

**Comment by AlexKolenoff** [comment]
@btfrise The issue I have had a couple of tickets for is possibly related to this one but a different result.  In two tickets I had, a user had a folder in trash with the same name as a folder they were using in the Image Folder widget, with files in that folder also with the same name, resulted in the images not showing on the display at all.  Deleting the folder from Trash corrected the issue.  Should this be logged as a separate bug?

**Comment by ByronDarlison** [comment]
@btfrise @AlexKolenoff @alanclayton @donnapep @stulees curious as to what you guys think priority of fixing this should be? Can it wait for another month?

Thanks!

FYI @tejohnso @fjvallarino

**Comment by fjvallarino** [comment]
@ByronDarlison This should be fixed by switching from Google API to Storage API. The PR is currently in review.

**Comment by ByronDarlison** [comment]
@fjvallarino perfect! Whose PR is it and who is it pending on? And, once that goes through can you put a note on this defect and let's retest and verify. Thanks!

**Comment by alanclayton** [comment]
@ByronDarlison @fjvallarino To confirm, this PR will bump the version of Storage Component. Once that is done Content team needs to update Image & Video Widgets. This is up next for @donnapep & @stulees .

**Comment by fjvallarino** [comment]
@stulees @donnapep @alanclayton The related PR has been merged and released as version 1.0.9

**Comment by ByronDarlison** [comment]
@fjvallarino @stulees @donnapep @alanclayton can you confirm this issue is now closed? FYI @alex-deaconu @ezequielc

**Comment by alanclayton** [comment]
@ByronDarlison Yes, this was resolved. Thanks
