### ISSUE TITLE
Files without datastore backing objects

### ISSUE THREAD

**Issue by tejohnso** [Rise-Vision/storage-server#209]
When requesting file contents a check is made to ensure that all returned files have an RvStorageObject.  If there is no such object, the file is not returned.   The server should also kick off a task to delete that file from GCS since it is no longer reachable and is invalid in the current system.
@fjvallarino Does the above sound right?

**Comment by ByronDarlison** [comment]
@tejohnso @fjvallarino is this issue still open?

**Comment by tejohnso** [comment]
@ByronDarlison It appears this is still open.  I don't think it's a problem unless we can show that orphaned files are causing an issue.

**Comment by ByronDarlison** [comment]
@tejohnso okay. I'd like to get it cleaned up. @alex-deaconu @ezequielc moving into the storage epic. Thanks

**Comment by ByronDarlison** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;wtenEE3i&#x2F;1128-https-github-com-rise-vision-storage-server-issues-209"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> https:&#x2F;&#x2F;github.com&#x2F;Rise-Vision&#x2F;storage-server&#x2F;issues&#x2F;209</a>
