### ISSUE TITLE
Files deleted from folder remain in generated xml/json

### ISSUE THREAD

**Issue by mfisher11** [Rise-Vision/storage-server#211]
Steps to reproduce:
1. Create a folder in storage
2. Upload file(s) to that folder
3. Get link to that folder and view generated xml/json
4. Delete a file from that folder
5. View the generated xml/json

Result:
Deleted file is still listed (even after two hours)

How it should work:
Deleted file should not be listed

Additional information:
This was noticed with the image folder widget.  Deleted files continue to be shown in presentation.
One difference I see when examining the output from storage is that "metageneration" equals 1 on files that are present and equals 2 on files that are deleted.  Is that what the widgets are supposed to look for/honor?  If that is the case (and the entries in the xml/json are not supposed to be removed), then this is actually a bug with the widget.

Link to Presentation:
http://rvauser.appspot.com/#/PRESENTATION_MANAGE/id=6a62f2c4-0122-41de-b207-af4e1d8fbb29?cid=fee1f642-cdd1-4bc4-8f93-1fc97cb00d55

OS:
Linux, Windows, OS X, Chrome OS

Chrome Ver:
43.0.2357.125  (technically stable, beta, and dev)

**Comment by fjvallarino** [comment]
@mfisher11 Is this happening in production or staging? When you say "deleted" does it mean "sent to trash" or "sent to trash and then deleted"? In case it's the second option, it's definitely an issue with storage.

There were some changes in the way storage handles deletions, which mean widgets need to consume our API (instead of Google Storage's one). There is a card related to that: https://trello.com/c/Wqn8ggUM/494-storage-component-updates

**Comment by mfisher11** [comment]
@fjvallarino This is happening in production.  I just selected the file(s) and hit the trash/delete button--so it was just moved to the trash.

Have the changes you're talking about already went into production?
Is this, then, a known issue with any folder widget (video, image)?

Thanks.

**Comment by fjvallarino** [comment]
@mfisher11 Those changes to Storage API are already in production. You can test using this URL: https://storage-dot-rvaserver2.appspot.com/_ah/api/storage/v0.01/files?companyId=fee1f642-cdd1-4bc4-8f93-1fc97cb00d55&folder=test%2F

I used the companyId you provided in the example presentation. You can change the folder parameter to the folder you were using for testing (or leave it empty in case you want to fetch files/folders in root)

**Comment by mfisher11** [comment]
@fjvallarino Okay.  Thanks for the info, sir.  I've verified that when emptying the trash, those entries are no longer present in the output from storage.

If you can confirm that this is the expected behavior (files remain in the storage xml/json output until removed from the trash; and that it is incumbent upon the widget to act on the metageneration tag (since that seems to be the deliminator))--I'll close this and open one in the image folder widget repo.

**Comment by fjvallarino** [comment]
@mfisher11 Widgets should not be using Google's API anymore. They should rely on Rise Vision Storage's one (the example URL I sent you). This is because we handle file operations with information contained in Datastore, which is not directly accessible (we merge information from both sources).

**Comment by mfisher11** [comment]
@fjvallarino @alanclayton Sorry about the misunderstanding.  Using the URL you provided, I've confirmed that it shows empty when expected, then shows a reference to a file once one is uploaded, and is removed again once deleted.  Thank you.   I'll close this out and update the card appropriately.
